spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1234

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html; charset=utf-8
    mode: HTML5
    encoding: UTF-8
    cache: false # 项目上线开启